owner: andreesg # Your GitHub username
repo: goncalves-upptime # Your Github repository name

sites:
  - name: Goncalves.me
    url: https://www.goncalves.me

status-website:
  baseUrl: /goncalves-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Monitor the uptime of https://www.goncalves.me"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
