owner: andreesg # Your GitHub username
repo: goncalves-upptime # Your Github repository name

sites:
  - name: Goncalves.me
    url: https://www.goncalves.me

status-website:
  cname: status.goncalves.me
  logoUrl: https://www.goncalves.me/img/3.png
  name: Goncalves.me
  introTitle: "Monitor the uptime of https://www.goncalves.me"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
